### ISSUE TITLE
upgrade sentry/sentry-laravel to support laravel 10

### ISSUE THREAD

**Issue by prhost** [OFFLINE-GmbH/oc-sentry-plugin#6]
Hello,

Would it be possible to update sentry/sentry-laravel to v3.x? I don't know if it would break something, but it supports laravel 10. and I can't use the package with laravel 10 :/

**Comment by tobias-kuendig** [comment]
You can fork this repo and change the composer.json requirement to `"sentry/sentry-laravel": "^3.0"` and see if/what breaks. Let me know if you need help setting this up.

I have not had the time to look into what changed from the Sentry 2.0 to the 3.0 release. 

Since I don't have the immediate need to use Laravel 10, I won't be working on this right away, so if someone wants to test it and provide a PR that would be great! :+1:

**Comment by prhost** [comment]
Hello @tobias-kuendig at first I tested it with last version 3.7.3 of sentry-laravel and everything is normal, it's triggering the error in the sentry with the log data. Send a PR?

**Comment by tobias-kuendig** [comment]
> Send a PR?

If you've got the code that would be great!

**Comment by prhost** [comment]
I only change the composer package `sentry-laravel` version from `2.0` to `^3.7.3` and I tested. I can send PR?

**Comment by tobias-kuendig** [comment]
Check out v3.0.0 of this plugin, it is using the latest Sentry SDK. Please be aware, that you need to migrate your DSN to your .env file. See README
